#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct. 

if [ "$CACHE_TAG" == "latest" ]; then

  LAST_GIT_TAG="$(git rev-list --tags --no-walk --max-count=1)"
  if [ -n "${LAST_GIT_TAG}" ]; then
    LAST_GIT_TAG="latest"
  fi
  
  BUILD_VERSION="${LAST_GIT_TAG}-rc${SOURCE_COMMIT}"
else
  BUILD_VERSION="$CACHE_TAG"
fi

docker build -f $DOCKERFILE_PATH \
  --build-arg VCS_REF=$(git rev-parse --short HEAD) \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg BUILD_VERSION="${BUILD_VERSION}"
  -t $IMAGE_NAME .

